---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Deployment.name }}
spec:
  replicas: {{ .Values.Deployment.replicas }}
  selector:
    matchLabels: {{ .Values.Deployment.labels | toYaml |nindent 6 }}
  template:
    metadata:
      labels: {{ .Values.Deployment.labels | toYaml | nindent 8 }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: {{ .Values.containers.name }}
          image: ghcr.io/azure-samples/aks-store-demo/product-service:{{ .Values.containers.tags }}
          ports:
          env:
            - name: AI_SERVICE_URL
              value: "http://ai-service:5001/"
          resources:  {{ .Values.containers.resources | toYaml | nindent 12}}
          readinessProbe:  {{ .Values.containers.readinessProbe | toYaml | nindent 12}}
          livenessProbe:  {{ .Values.containers.livenessProbe | toYaml | nindent 12}}
            
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: ClusterIP
  ports: {{ .Values.service.ports | toYaml | nindent 4}}
  selector: {{ .Values.service.ports | toYaml | nindent 6 }}
